name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm and install Railway CLI
        run: |
          npm install -g pnpm
          pnpm setup
          export PATH="$PNPM_HOME:$PATH"
          pnpm add -g @railway/cli
          railway --version  # optional: cek versi CLI

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          export PATH="$PNPM_HOME:$PATH"
          railway up
